export const GET_ALL_DISEASES_REQUEST = "GET_ALL_DISEASES_REQUEST"
export const GET_ALL_DISEASES_SUCCESS = "GET_ALL_DISEASES_SUCCESS"
export const GET_ALL_DISEASES_FAILURE = "GET_ALL_DISEASES_FAILURE"

